import { TokenSet, Token } from "../types";

type colorBox = {
  [key: string]: colorStep[];
}

type colorStep = {
  step: string;
  hex: string;
  lightness: number;
  chroma: number;
  oklchHue: number;
  oklchString: string;
  hue: number;
  saturation: number;
  brightness: number;
}

/*
  Color primitives generated by https://colorbox.io/
  color-config.json can be imported into colorbox to adjust
*/
const colorBoxOutput: colorBox = {
  "warm": [
    {
      "step": "0",
      "hex": "#f0eeeb",
      "lightness": 95,
      "chroma": 0.005,
      "oklchHue": 83,
      "oklchString": "oklch(95.0% 0.005 83.0)",
      "hue": 39,
      "saturation": 2.2,
      "brightness": 94.11
    },
    {
      "step": "25",
      "hex": "#eeece8",
      "lightness": 94.3,
      "chroma": 0.005,
      "oklchHue": 83,
      "oklchString": "oklch(94.3% 0.005 83.0)",
      "hue": 39,
      "saturation": 2.34,
      "brightness": 93.28
    },
    {
      "step": "50",
      "hex": "#eceae6",
      "lightness": 93.7,
      "chroma": 0.006,
      "oklchHue": 83,
      "oklchString": "oklch(93.7% 0.006 83.0)",
      "hue": 39,
      "saturation": 2.48,
      "brightness": 92.44
    },
    {
      "step": "100",
      "hex": "#e7e5e1",
      "lightness": 92.3,
      "chroma": 0.006,
      "oklchHue": 83,
      "oklchString": "oklch(92.3% 0.006 83.0)",
      "hue": 39,
      "saturation": 2.77,
      "brightness": 90.78
    },
    {
      "step": "150",
      "hex": "#dddbd6",
      "lightness": 89.1,
      "chroma": 0.007,
      "oklchHue": 83,
      "oklchString": "oklch(89.1% 0.007 83.0)",
      "hue": 39,
      "saturation": 3.14,
      "brightness": 86.72
    },
    {
      "step": "200",
      "hex": "#d3d0cb",
      "lightness": 85.9,
      "chroma": 0.007,
      "oklchHue": 83,
      "oklchString": "oklch(85.9% 0.007 83.0)",
      "hue": 39,
      "saturation": 3.53,
      "brightness": 82.69
    },
    {
      "step": "250",
      "hex": "#c2bfba",
      "lightness": 80.6,
      "chroma": 0.008,
      "oklchHue": 83,
      "oklchString": "oklch(80.6% 0.008 83.0)",
      "hue": 39,
      "saturation": 4.07,
      "brightness": 76.09
    },
    {
      "step": "300",
      "hex": "#b1afa9",
      "lightness": 75.3,
      "chroma": 0.008,
      "oklchHue": 83,
      "oklchString": "oklch(75.3% 0.008 83.0)",
      "hue": 39,
      "saturation": 4.69,
      "brightness": 69.59
    },
    {
      "step": "350",
      "hex": "#9c9893",
      "lightness": 68.2,
      "chroma": 0.009,
      "oklchHue": 83,
      "oklchString": "oklch(68.2% 0.009 83.0)",
      "hue": 39,
      "saturation": 5.57,
      "brightness": 60.99
    },
    {
      "step": "400",
      "hex": "#86837d",
      "lightness": 61.1,
      "chroma": 0.009,
      "oklchHue": 83,
      "oklchString": "oklch(61.1% 0.009 83.0)",
      "hue": 39,
      "saturation": 6.69,
      "brightness": 52.61
    },
    {
      "step": "450",
      "hex": "#6f6c66",
      "lightness": 53.2,
      "chroma": 0.01,
      "oklchHue": 83,
      "oklchString": "oklch(53.2% 0.010 83.0)",
      "hue": 39,
      "saturation": 8.26,
      "brightness": 43.63
    },
    {
      "step": "500",
      "hex": "#595650",
      "lightness": 45.4,
      "chroma": 0.011,
      "oklchHue": 83,
      "oklchString": "oklch(45.4% 0.011 83.0)",
      "hue": 39,
      "saturation": 10.47,
      "brightness": 34.97
    },
    {
      "step": "550",
      "hex": "#46433d",
      "lightness": 38.3,
      "chroma": 0.011,
      "oklchHue": 83,
      "oklchString": "oklch(38.3% 0.011 83.0)",
      "hue": 39,
      "saturation": 13.46,
      "brightness": 27.51
    },
    {
      "step": "600",
      "hex": "#34312a",
      "lightness": 31.3,
      "chroma": 0.012,
      "oklchHue": 83,
      "oklchString": "oklch(31.3% 0.012 83.0)",
      "hue": 39,
      "saturation": 18.2,
      "brightness": 20.37
    },
    {
      "step": "650",
      "hex": "#27241e",
      "lightness": 26.1,
      "chroma": 0.012,
      "oklchHue": 83,
      "oklchString": "oklch(26.1% 0.012 83.0)",
      "hue": 39,
      "saturation": 24.27,
      "brightness": 15.36
    },
    {
      "step": "700",
      "hex": "#1b1811",
      "lightness": 20.9,
      "chroma": 0.013,
      "oklchHue": 83,
      "oklchString": "oklch(20.9% 0.013 83.0)",
      "hue": 39,
      "saturation": 35.11,
      "brightness": 10.57
    },
    {
      "step": "750",
      "hex": "#14110a",
      "lightness": 17.8,
      "chroma": 0.013,
      "oklchHue": 83,
      "oklchString": "oklch(17.8% 0.013 83.0)",
      "hue": 39.1,
      "saturation": 47.92,
      "brightness": 7.82
    },
    {
      "step": "800",
      "hex": "#0d0a05",
      "lightness": 14.6,
      "chroma": 0.014,
      "oklchHue": 83,
      "oklchString": "oklch(14.6% 0.014 83.0)",
      "hue": 36.4,
      "saturation": 64.04,
      "brightness": 5.18
    },
    {
      "step": "850",
      "hex": "#0b0703",
      "lightness": 13.3,
      "chroma": 0.014,
      "oklchHue": 83,
      "oklchString": "oklch(13.3% 0.014 83.0)",
      "hue": 34.6,
      "saturation": 70.87,
      "brightness": 4.13
    },
    {
      "step": "900",
      "hex": "#080502",
      "lightness": 12,
      "chroma": 0.015,
      "oklchHue": 83,
      "oklchString": "oklch(12.0% 0.015 83.0)",
      "hue": 33.9,
      "saturation": 77.49,
      "brightness": 3.16
    }
  ],
  "cool": [
    {
      "step": "0",
      "hex": "#e9eff9",
      "lightness": 95,
      "chroma": 0.015,
      "oklchHue": 264,
      "oklchString": "oklch(95.0% 0.015 264.0)",
      "hue": 219.7,
      "saturation": 6.27,
      "brightness": 97.63
    },
    {
      "step": "25",
      "hex": "#e7ecf7",
      "lightness": 94.3,
      "chroma": 0.016,
      "oklchHue": 264,
      "oklchString": "oklch(94.3% 0.016 264.0)",
      "hue": 219.7,
      "saturation": 6.65,
      "brightness": 96.98
    },
    {
      "step": "50",
      "hex": "#e4eaf6",
      "lightness": 93.7,
      "chroma": 0.017,
      "oklchHue": 264,
      "oklchString": "oklch(93.7% 0.017 264.0)",
      "hue": 219.7,
      "saturation": 7.03,
      "brightness": 96.33
    },
    {
      "step": "100",
      "hex": "#dfe6f2",
      "lightness": 92.3,
      "chroma": 0.018,
      "oklchHue": 264,
      "oklchString": "oklch(92.3% 0.018 264.0)",
      "hue": 219.7,
      "saturation": 7.81,
      "brightness": 95.03
    },
    {
      "step": "150",
      "hex": "#d4dbe9",
      "lightness": 89.1,
      "chroma": 0.02,
      "oklchHue": 264,
      "oklchString": "oklch(89.1% 0.020 264.0)",
      "hue": 219.7,
      "saturation": 8.78,
      "brightness": 91.31
    },
    {
      "step": "200",
      "hex": "#c9d1df",
      "lightness": 85.9,
      "chroma": 0.022,
      "oklchHue": 264,
      "oklchString": "oklch(85.9% 0.022 264.0)",
      "hue": 219.7,
      "saturation": 9.82,
      "brightness": 87.62
    },
    {
      "step": "250",
      "hex": "#b8c0cf",
      "lightness": 80.6,
      "chroma": 0.023,
      "oklchHue": 264,
      "oklchString": "oklch(80.6% 0.023 264.0)",
      "hue": 219.7,
      "saturation": 11.2,
      "brightness": 81.3
    },
    {
      "step": "300",
      "hex": "#a7afbf",
      "lightness": 75.3,
      "chroma": 0.025,
      "oklchHue": 264,
      "oklchString": "oklch(75.3% 0.025 264.0)",
      "hue": 219.7,
      "saturation": 12.77,
      "brightness": 75.06
    },
    {
      "step": "350",
      "hex": "#9199aa",
      "lightness": 68.2,
      "chroma": 0.027,
      "oklchHue": 264,
      "oklchString": "oklch(68.2% 0.027 264.0)",
      "hue": 219.7,
      "saturation": 14.94,
      "brightness": 66.67
    },
    {
      "step": "400",
      "hex": "#7b8495",
      "lightness": 61.1,
      "chroma": 0.028,
      "oklchHue": 264,
      "oklchString": "oklch(61.1% 0.028 264.0)",
      "hue": 219.8,
      "saturation": 17.58,
      "brightness": 58.46
    },
    {
      "step": "450",
      "hex": "#646d7e",
      "lightness": 53.2,
      "chroma": 0.03,
      "oklchHue": 264,
      "oklchString": "oklch(53.2% 0.030 264.0)",
      "hue": 219.8,
      "saturation": 21.17,
      "brightness": 49.58
    },
    {
      "step": "500",
      "hex": "#4d5668",
      "lightness": 45.4,
      "chroma": 0.032,
      "oklchHue": 264,
      "oklchString": "oklch(45.4% 0.032 264.0)",
      "hue": 219.9,
      "saturation": 25.92,
      "brightness": 40.97
    },
    {
      "step": "550",
      "hex": "#3a4355",
      "lightness": 38.3,
      "chroma": 0.033,
      "oklchHue": 264,
      "oklchString": "oklch(38.3% 0.033 264.0)",
      "hue": 220,
      "saturation": 31.88,
      "brightness": 33.52
    },
    {
      "step": "600",
      "hex": "#283143",
      "lightness": 31.3,
      "chroma": 0.035,
      "oklchHue": 264,
      "oklchString": "oklch(31.3% 0.035 264.0)",
      "hue": 220.1,
      "saturation": 40.39,
      "brightness": 26.32
    },
    {
      "step": "650",
      "hex": "#1b2436",
      "lightness": 26.1,
      "chroma": 0.037,
      "oklchHue": 264,
      "oklchString": "oklch(26.1% 0.037 264.0)",
      "hue": 220.3,
      "saturation": 49.92,
      "brightness": 21.26
    },
    {
      "step": "700",
      "hex": "#0f182a",
      "lightness": 20.9,
      "chroma": 0.038,
      "oklchHue": 264,
      "oklchString": "oklch(20.9% 0.038 264.0)",
      "hue": 220.6,
      "saturation": 64.05,
      "brightness": 16.35
    },
    {
      "step": "750",
      "hex": "#081023",
      "lightness": 17.8,
      "chroma": 0.04,
      "oklchHue": 264,
      "oklchString": "oklch(17.8% 0.040 264.0)",
      "hue": 221.2,
      "saturation": 76.89,
      "brightness": 13.56
    },
    {
      "step": "800",
      "hex": "#03091c",
      "lightness": 14.6,
      "chroma": 0.042,
      "oklchHue": 264,
      "oklchString": "oklch(14.6% 0.042 264.0)",
      "hue": 225.3,
      "saturation": 88.13,
      "brightness": 10.83
    },
    {
      "step": "850",
      "hex": "#020719",
      "lightness": 13.3,
      "chroma": 0.043,
      "oklchHue": 264,
      "oklchString": "oklch(13.3% 0.043 264.0)",
      "hue": 227.9,
      "saturation": 92.29,
      "brightness": 9.84
    },
    {
      "step": "900",
      "hex": "#010417",
      "lightness": 12,
      "chroma": 0.045,
      "oklchHue": 264,
      "oklchString": "oklch(12.0% 0.045 264.0)",
      "hue": 230.4,
      "saturation": 95.58,
      "brightness": 8.86
    }
  ],
  "blue": [
    {
      "step": "0",
      "hex": "#e3f0ff",
      "lightness": 95,
      "chroma": 0.025,
      "oklchHue": 250,
      "oklchString": "oklch(95.0% 0.025 250.0)",
      "hue": 211.1,
      "saturation": 11.12,
      "brightness": 99.96
    },
    {
      "step": "25",
      "hex": "#dfeeff",
      "lightness": 94.3,
      "chroma": 0.028,
      "oklchHue": 250.6,
      "oklchString": "oklch(94.3% 0.028 250.6)",
      "hue": 211.4,
      "saturation": 12.55,
      "brightness": 99.96
    },
    {
      "step": "50",
      "hex": "#dbecff",
      "lightness": 93.7,
      "chroma": 0.031,
      "oklchHue": 251.1,
      "oklchString": "oklch(93.7% 0.031 251.1)",
      "hue": 211.7,
      "saturation": 13.97,
      "brightness": 99.96
    },
    {
      "step": "100",
      "hex": "#d4e8ff",
      "lightness": 92.3,
      "chroma": 0.038,
      "oklchHue": 252.2,
      "oklchString": "oklch(92.3% 0.038 252.2)",
      "hue": 212.3,
      "saturation": 16.76,
      "brightness": 99.95
    },
    {
      "step": "150",
      "hex": "#c3deff",
      "lightness": 89.1,
      "chroma": 0.054,
      "oklchHue": 253.3,
      "oklchString": "oklch(89.1% 0.054 253.3)",
      "hue": 212.9,
      "saturation": 23.59,
      "brightness": 99.95
    },
    {
      "step": "200",
      "hex": "#b2d4ff",
      "lightness": 85.9,
      "chroma": 0.07,
      "oklchHue": 254.4,
      "oklchString": "oklch(85.9% 0.070 254.4)",
      "hue": 213.5,
      "saturation": 30.21,
      "brightness": 99.88
    },
    {
      "step": "250",
      "hex": "#95c3ff",
      "lightness": 80.6,
      "chroma": 0.099,
      "oklchHue": 255.6,
      "oklchString": "oklch(80.6% 0.099 255.6)",
      "hue": 214.1,
      "saturation": 41.48,
      "brightness": 99.92
    },
    {
      "step": "300",
      "hex": "#79b1fe",
      "lightness": 75.3,
      "chroma": 0.127,
      "oklchHue": 256.7,
      "oklchString": "oklch(75.3% 0.127 256.7)",
      "hue": 214.8,
      "saturation": 52.42,
      "brightness": 99.73
    },
    {
      "step": "350",
      "hex": "#5298fd",
      "lightness": 68.2,
      "chroma": 0.166,
      "oklchHue": 257.8,
      "oklchString": "oklch(68.2% 0.166 257.8)",
      "hue": 215.5,
      "saturation": 67.7,
      "brightness": 99.38
    },
    {
      "step": "400",
      "hex": "#277dfc",
      "lightness": 61.1,
      "chroma": 0.206,
      "oklchHue": 258.9,
      "oklchString": "oklch(61.1% 0.206 258.9)",
      "hue": 215.7,
      "saturation": 84.56,
      "brightness": 98.63
    },
    {
      "step": "450",
      "hex": "#1563de",
      "lightness": 53.2,
      "chroma": 0.201,
      "oklchHue": 260,
      "oklchString": "oklch(53.2% 0.201 260.0)",
      "hue": 216.5,
      "saturation": 90.67,
      "brightness": 86.9
    },
    {
      "step": "500",
      "hex": "#024ac0",
      "lightness": 45.4,
      "chroma": 0.196,
      "oklchHue": 261.1,
      "oklchString": "oklch(45.4% 0.196 261.1)",
      "hue": 217.2,
      "saturation": 99.16,
      "brightness": 75.38
    },
    {
      "step": "550",
      "hex": "#0136a0",
      "lightness": 38.3,
      "chroma": 0.179,
      "oklchHue": 262.2,
      "oklchString": "oklch(38.3% 0.179 262.2)",
      "hue": 220.1,
      "saturation": 99.6,
      "brightness": 62.83
    },
    {
      "step": "600",
      "hex": "#002281",
      "lightness": 31.3,
      "chroma": 0.163,
      "oklchHue": 263.3,
      "oklchString": "oklch(31.3% 0.163 263.3)",
      "hue": 224.4,
      "saturation": 99.83,
      "brightness": 50.68
    },
    {
      "step": "650",
      "hex": "#01126c",
      "lightness": 26.1,
      "chroma": 0.152,
      "oklchHue": 264.4,
      "oklchString": "oklch(26.1% 0.152 264.4)",
      "hue": 230.7,
      "saturation": 98.95,
      "brightness": 42.33
    },
    {
      "step": "700",
      "hex": "#020157",
      "lightness": 20.9,
      "chroma": 0.142,
      "oklchHue": 265.6,
      "oklchString": "oklch(20.9% 0.142 265.6)",
      "hue": 241.1,
      "saturation": 99.38,
      "brightness": 34.22
    },
    {
      "step": "750",
      "hex": "#020044",
      "lightness": 17.8,
      "chroma": 0.119,
      "oklchHue": 266.7,
      "oklchString": "oklch(17.8% 0.119 266.7)",
      "hue": 241.9,
      "saturation": 99.65,
      "brightness": 26.74
    },
    {
      "step": "800",
      "hex": "#020032",
      "lightness": 14.6,
      "chroma": 0.097,
      "oklchHue": 267.8,
      "oklchString": "oklch(14.6% 0.097 267.8)",
      "hue": 242.1,
      "saturation": 99.65,
      "brightness": 19.59
    },
    {
      "step": "850",
      "hex": "#02002b",
      "lightness": 13.3,
      "chroma": 0.088,
      "oklchHue": 268.9,
      "oklchString": "oklch(13.3% 0.088 268.9)",
      "hue": 242.5,
      "saturation": 99.8,
      "brightness": 16.69
    },
    {
      "step": "900",
      "hex": "#020023",
      "lightness": 12,
      "chroma": 0.078,
      "oklchHue": 270,
      "oklchString": "oklch(12.0% 0.078 270.0)",
      "hue": 242.7,
      "saturation": 99.84,
      "brightness": 13.86
    }
  ],
  "teal": [
    {
      "step": "0",
      "hex": "#ecfcff",
      "lightness": 98,
      "chroma": 0.017,
      "oklchHue": 210,
      "oklchString": "oklch(98.0% 0.017 210.0)",
      "hue": 189.4,
      "saturation": 7.53,
      "brightness": 100
    },
    {
      "step": "25",
      "hex": "#e5fbff",
      "lightness": 97.3,
      "chroma": 0.023,
      "oklchHue": 210.3,
      "oklchString": "oklch(97.3% 0.023 210.3)",
      "hue": 189.5,
      "saturation": 10.07,
      "brightness": 99.97
    },
    {
      "step": "50",
      "hex": "#dffaff",
      "lightness": 96.6,
      "chroma": 0.029,
      "oklchHue": 210.6,
      "oklchString": "oklch(96.6% 0.029 210.6)",
      "hue": 189.7,
      "saturation": 12.65,
      "brightness": 99.95
    },
    {
      "step": "100",
      "hex": "#d1f7ff",
      "lightness": 95.2,
      "chroma": 0.041,
      "oklchHue": 211.1,
      "oklchString": "oklch(95.2% 0.041 211.1)",
      "hue": 190,
      "saturation": 17.92,
      "brightness": 99.94
    },
    {
      "step": "150",
      "hex": "#aff1ff",
      "lightness": 91.9,
      "chroma": 0.069,
      "oklchHue": 211.7,
      "oklchString": "oklch(91.9% 0.069 211.7)",
      "hue": 190.2,
      "saturation": 31.42,
      "brightness": 99.93
    },
    {
      "step": "200",
      "hex": "#88ebff",
      "lightness": 88.6,
      "chroma": 0.097,
      "oklchHue": 212.2,
      "oklchString": "oklch(88.6% 0.097 212.2)",
      "hue": 190.1,
      "saturation": 46.66,
      "brightness": 99.94
    },
    {
      "step": "250",
      "hex": "#5ddbf4",
      "lightness": 83.1,
      "chroma": 0.116,
      "oklchHue": 212.8,
      "oklchString": "oklch(83.1% 0.116 212.8)",
      "hue": 189.9,
      "saturation": 61.99,
      "brightness": 95.74
    },
    {
      "step": "300",
      "hex": "#0eccea",
      "lightness": 77.6,
      "chroma": 0.135,
      "oklchHue": 213.3,
      "oklchString": "oklch(77.6% 0.135 213.3)",
      "hue": 188.2,
      "saturation": 94.15,
      "brightness": 91.58
    },
    {
      "step": "350",
      "hex": "#08b2cd",
      "lightness": 70.3,
      "chroma": 0.122,
      "oklchHue": 213.9,
      "oklchString": "oklch(70.3% 0.122 213.9)",
      "hue": 188.3,
      "saturation": 95.99,
      "brightness": 80.51
    },
    {
      "step": "400",
      "hex": "#0499b2",
      "lightness": 62.9,
      "chroma": 0.11,
      "oklchHue": 214.4,
      "oklchString": "oklch(62.9% 0.110 214.4)",
      "hue": 188.5,
      "saturation": 97.97,
      "brightness": 69.67
    },
    {
      "step": "450",
      "hex": "#027e94",
      "lightness": 54.7,
      "chroma": 0.096,
      "oklchHue": 215,
      "oklchString": "oklch(54.7% 0.096 215.0)",
      "hue": 188.8,
      "saturation": 98.75,
      "brightness": 57.93
    },
    {
      "step": "500",
      "hex": "#006577",
      "lightness": 46.6,
      "chroma": 0.082,
      "oklchHue": 215.6,
      "oklchString": "oklch(46.6% 0.082 215.6)",
      "hue": 189.1,
      "saturation": 99.63,
      "brightness": 46.56
    },
    {
      "step": "550",
      "hex": "#014f5e",
      "lightness": 39.3,
      "chroma": 0.07,
      "oklchHue": 216.1,
      "oklchString": "oklch(39.3% 0.070 216.1)",
      "hue": 189.6,
      "saturation": 99.08,
      "brightness": 36.69
    },
    {
      "step": "600",
      "hex": "#013a45",
      "lightness": 32,
      "chroma": 0.057,
      "oklchHue": 216.7,
      "oklchString": "oklch(32.0% 0.057 216.7)",
      "hue": 190.3,
      "saturation": 98.83,
      "brightness": 27.22
    },
    {
      "step": "650",
      "hex": "#002b34",
      "lightness": 26.6,
      "chroma": 0.047,
      "oklchHue": 217.2,
      "oklchString": "oklch(26.6% 0.047 217.2)",
      "hue": 191.1,
      "saturation": 99.26,
      "brightness": 20.59
    },
    {
      "step": "700",
      "hex": "#001d24",
      "lightness": 21.2,
      "chroma": 0.038,
      "oklchHue": 217.8,
      "oklchString": "oklch(21.2% 0.038 217.8)",
      "hue": 192.4,
      "saturation": 99.74,
      "brightness": 14.25
    },
    {
      "step": "750",
      "hex": "#00151b",
      "lightness": 18,
      "chroma": 0.032,
      "oklchHue": 218.3,
      "oklchString": "oklch(18.0% 0.032 218.3)",
      "hue": 193.9,
      "saturation": 99.78,
      "brightness": 10.59
    },
    {
      "step": "800",
      "hex": "#000d12",
      "lightness": 14.7,
      "chroma": 0.027,
      "oklchHue": 218.9,
      "oklchString": "oklch(14.7% 0.027 218.9)",
      "hue": 196.6,
      "saturation": 99.89,
      "brightness": 7.08
    },
    {
      "step": "850",
      "hex": "#000a0e",
      "lightness": 13.4,
      "chroma": 0.024,
      "oklchHue": 219.4,
      "oklchString": "oklch(13.4% 0.024 219.4)",
      "hue": 198.8,
      "saturation": 99.92,
      "brightness": 5.68
    },
    {
      "step": "900",
      "hex": "#00070b",
      "lightness": 12,
      "chroma": 0.022,
      "oklchHue": 220,
      "oklchString": "oklch(12.0% 0.022 220.0)",
      "hue": 200.7,
      "saturation": 100,
      "brightness": 4.31
    }
  ],
  "green": [
    {
      "step": "0",
      "hex": "#ecffe8",
      "lightness": 98,
      "chroma": 0.036,
      "oklchHue": 140,
      "oklchString": "oklch(98.0% 0.036 140.0)",
      "hue": 109.1,
      "saturation": 9.01,
      "brightness": 99.99
    },
    {
      "step": "25",
      "hex": "#e5ffe0",
      "lightness": 97.3,
      "chroma": 0.049,
      "oklchHue": 140.8,
      "oklchString": "oklch(97.3% 0.049 140.8)",
      "hue": 110.8,
      "saturation": 12.02,
      "brightness": 99.99
    },
    {
      "step": "50",
      "hex": "#deffd9",
      "lightness": 96.6,
      "chroma": 0.061,
      "oklchHue": 141.7,
      "oklchString": "oklch(96.6% 0.061 141.7)",
      "hue": 112.5,
      "saturation": 14.96,
      "brightness": 99.99
    },
    {
      "step": "100",
      "hex": "#ceffca",
      "lightness": 95.2,
      "chroma": 0.086,
      "oklchHue": 143.3,
      "oklchString": "oklch(95.2% 0.086 143.3)",
      "hue": 116.4,
      "saturation": 20.62,
      "brightness": 99.99
    },
    {
      "step": "150",
      "hex": "#b3f9b4",
      "lightness": 91.9,
      "chroma": 0.117,
      "oklchHue": 145,
      "oklchString": "oklch(91.9% 0.117 145.0)",
      "hue": 121.1,
      "saturation": 28.39,
      "brightness": 97.79
    },
    {
      "step": "200",
      "hex": "#94f49e",
      "lightness": 88.6,
      "chroma": 0.148,
      "oklchHue": 146.7,
      "oklchString": "oklch(88.6% 0.148 146.7)",
      "hue": 126.4,
      "saturation": 39.21,
      "brightness": 95.56
    },
    {
      "step": "250",
      "hex": "#74e48a",
      "lightness": 83.1,
      "chroma": 0.162,
      "oklchHue": 148.3,
      "oklchString": "oklch(83.1% 0.162 148.3)",
      "hue": 131.7,
      "saturation": 49.04,
      "brightness": 89.45
    },
    {
      "step": "300",
      "hex": "#4ed577",
      "lightness": 77.6,
      "chroma": 0.177,
      "oklchHue": 150,
      "oklchString": "oklch(77.6% 0.177 150.0)",
      "hue": 137.9,
      "saturation": 63.11,
      "brightness": 83.37
    },
    {
      "step": "350",
      "hex": "#32bc67",
      "lightness": 70.3,
      "chroma": 0.168,
      "oklchHue": 151.7,
      "oklchString": "oklch(70.3% 0.168 151.7)",
      "hue": 143.3,
      "saturation": 73.53,
      "brightness": 73.62
    },
    {
      "step": "400",
      "hex": "#04a358",
      "lightness": 62.9,
      "chroma": 0.16,
      "oklchHue": 153.3,
      "oklchString": "oklch(62.9% 0.160 153.3)",
      "hue": 151.6,
      "saturation": 97.44,
      "brightness": 64.06
    },
    {
      "step": "450",
      "hex": "#04874c",
      "lightness": 54.7,
      "chroma": 0.134,
      "oklchHue": 155,
      "oklchString": "oklch(54.7% 0.134 155.0)",
      "hue": 153.2,
      "saturation": 97.18,
      "brightness": 52.86
    },
    {
      "step": "500",
      "hex": "#006c3f",
      "lightness": 46.6,
      "chroma": 0.111,
      "oklchHue": 156.7,
      "oklchString": "oklch(46.6% 0.111 156.7)",
      "hue": 155,
      "saturation": 99.54,
      "brightness": 42.16
    },
    {
      "step": "550",
      "hex": "#015433",
      "lightness": 39.3,
      "chroma": 0.091,
      "oklchHue": 158.3,
      "oklchString": "oklch(39.3% 0.091 158.3)",
      "hue": 155.9,
      "saturation": 98.55,
      "brightness": 32.93
    },
    {
      "step": "600",
      "hex": "#013e26",
      "lightness": 32,
      "chroma": 0.072,
      "oklchHue": 160,
      "oklchString": "oklch(32.0% 0.072 160.0)",
      "hue": 156.5,
      "saturation": 99.13,
      "brightness": 24.18
    },
    {
      "step": "650",
      "hex": "#002e1c",
      "lightness": 26.6,
      "chroma": 0.058,
      "oklchHue": 161.7,
      "oklchString": "oklch(26.6% 0.058 161.7)",
      "hue": 156.8,
      "saturation": 98.92,
      "brightness": 18.03
    },
    {
      "step": "700",
      "hex": "#001f13",
      "lightness": 21.2,
      "chroma": 0.046,
      "oklchHue": 163.3,
      "oklchString": "oklch(21.2% 0.046 163.3)",
      "hue": 156.1,
      "saturation": 99.66,
      "brightness": 12.22
    },
    {
      "step": "750",
      "hex": "#00170d",
      "lightness": 18,
      "chroma": 0.038,
      "oklchHue": 165,
      "oklchString": "oklch(18.0% 0.038 165.0)",
      "hue": 155.2,
      "saturation": 99.37,
      "brightness": 8.86
    },
    {
      "step": "800",
      "hex": "#000e08",
      "lightness": 14.7,
      "chroma": 0.03,
      "oklchHue": 166.7,
      "oklchString": "oklch(14.7% 0.030 166.7)",
      "hue": 152.7,
      "saturation": 99.9,
      "brightness": 5.68
    },
    {
      "step": "850",
      "hex": "#000b06",
      "lightness": 13.4,
      "chroma": 0.027,
      "oklchHue": 168.3,
      "oklchString": "oklch(13.4% 0.027 168.3)",
      "hue": 153.3,
      "saturation": 99.37,
      "brightness": 4.37
    },
    {
      "step": "900",
      "hex": "#000805",
      "lightness": 12,
      "chroma": 0.024,
      "oklchHue": 170,
      "oklchString": "oklch(12.0% 0.024 170.0)",
      "hue": 154.9,
      "saturation": 99.77,
      "brightness": 3.17
    }
  ],
  "lime": [
    {
      "step": "0",
      "hex": "#f1ffdb",
      "lightness": 98,
      "chroma": 0.049,
      "oklchHue": 125,
      "oklchString": "oklch(98.0% 0.049 125.0)",
      "hue": 83.9,
      "saturation": 14.15,
      "brightness": 100
    },
    {
      "step": "25",
      "hex": "#ecffcc",
      "lightness": 97.3,
      "chroma": 0.069,
      "oklchHue": 124.6,
      "oklchString": "oklch(97.3% 0.069 124.6)",
      "hue": 82.8,
      "saturation": 19.84,
      "brightness": 99.98
    },
    {
      "step": "50",
      "hex": "#e7ffbc",
      "lightness": 96.6,
      "chroma": 0.09,
      "oklchHue": 124.2,
      "oklchString": "oklch(96.6% 0.090 124.2)",
      "hue": 81.6,
      "saturation": 26.26,
      "brightness": 99.98
    },
    {
      "step": "100",
      "hex": "#ddff94",
      "lightness": 95.2,
      "chroma": 0.138,
      "oklchHue": 123.3,
      "oklchString": "oklch(95.2% 0.138 123.3)",
      "hue": 78.9,
      "saturation": 41.92,
      "brightness": 99.95
    },
    {
      "step": "150",
      "hex": "#d0f666",
      "lightness": 91.9,
      "chroma": 0.175,
      "oklchHue": 122.5,
      "oklchString": "oklch(91.9% 0.175 122.5)",
      "hue": 76,
      "saturation": 58.81,
      "brightness": 96.65
    },
    {
      "step": "200",
      "hex": "#c4ed07",
      "lightness": 88.6,
      "chroma": 0.213,
      "oklchHue": 121.7,
      "oklchString": "oklch(88.6% 0.213 121.7)",
      "hue": 70.9,
      "saturation": 96.98,
      "brightness": 93.11
    },
    {
      "step": "250",
      "hex": "#b6d906",
      "lightness": 83.1,
      "chroma": 0.198,
      "oklchHue": 120.8,
      "oklchString": "oklch(83.1% 0.198 120.8)",
      "hue": 70.1,
      "saturation": 97.09,
      "brightness": 85.25
    },
    {
      "step": "300",
      "hex": "#a8c607",
      "lightness": 77.6,
      "chroma": 0.183,
      "oklchHue": 120,
      "oklchString": "oklch(77.6% 0.183 120.0)",
      "hue": 69.3,
      "saturation": 96.27,
      "brightness": 77.57
    },
    {
      "step": "350",
      "hex": "#95ac04",
      "lightness": 70.3,
      "chroma": 0.164,
      "oklchHue": 119.2,
      "oklchString": "oklch(70.3% 0.164 119.2)",
      "hue": 68.5,
      "saturation": 97.42,
      "brightness": 67.6
    },
    {
      "step": "400",
      "hex": "#819404",
      "lightness": 62.9,
      "chroma": 0.146,
      "oklchHue": 118.3,
      "oklchString": "oklch(62.9% 0.146 118.3)",
      "hue": 67.8,
      "saturation": 97.52,
      "brightness": 57.94
    },
    {
      "step": "450",
      "hex": "#6c7a01",
      "lightness": 54.7,
      "chroma": 0.126,
      "oklchHue": 117.5,
      "oklchString": "oklch(54.7% 0.126 117.5)",
      "hue": 67,
      "saturation": 98.98,
      "brightness": 47.69
    },
    {
      "step": "500",
      "hex": "#566101",
      "lightness": 46.6,
      "chroma": 0.107,
      "oklchHue": 116.7,
      "oklchString": "oklch(46.6% 0.107 116.7)",
      "hue": 66.3,
      "saturation": 99.45,
      "brightness": 37.86
    },
    {
      "step": "550",
      "hex": "#444b00",
      "lightness": 39.3,
      "chroma": 0.089,
      "oklchHue": 115.8,
      "oklchString": "oklch(39.3% 0.089 115.8)",
      "hue": 65.7,
      "saturation": 99.47,
      "brightness": 29.44
    },
    {
      "step": "600",
      "hex": "#323701",
      "lightness": 32,
      "chroma": 0.072,
      "oklchHue": 115,
      "oklchString": "oklch(32.0% 0.072 115.0)",
      "hue": 65.2,
      "saturation": 98.97,
      "brightness": 21.44
    },
    {
      "step": "650",
      "hex": "#252800",
      "lightness": 26.6,
      "chroma": 0.06,
      "oklchHue": 114.2,
      "oklchString": "oklch(26.6% 0.060 114.2)",
      "hue": 64.7,
      "saturation": 99.59,
      "brightness": 15.84
    },
    {
      "step": "700",
      "hex": "#191b00",
      "lightness": 21.2,
      "chroma": 0.047,
      "oklchHue": 113.3,
      "oklchString": "oklch(21.2% 0.047 113.3)",
      "hue": 64.2,
      "saturation": 99.82,
      "brightness": 10.55
    },
    {
      "step": "750",
      "hex": "#121300",
      "lightness": 18,
      "chroma": 0.04,
      "oklchHue": 112.5,
      "oklchString": "oklch(18.0% 0.040 112.5)",
      "hue": 63.7,
      "saturation": 99.87,
      "brightness": 7.49
    },
    {
      "step": "800",
      "hex": "#0b0c00",
      "lightness": 14.7,
      "chroma": 0.032,
      "oklchHue": 111.7,
      "oklchString": "oklch(14.7% 0.032 111.7)",
      "hue": 63.2,
      "saturation": 99.71,
      "brightness": 4.59
    },
    {
      "step": "850",
      "hex": "#080900",
      "lightness": 13.4,
      "chroma": 0.029,
      "oklchHue": 110.8,
      "oklchString": "oklch(13.4% 0.029 110.8)",
      "hue": 61.9,
      "saturation": 99.87,
      "brightness": 3.43
    },
    {
      "step": "900",
      "hex": "#060600",
      "lightness": 12,
      "chroma": 0.026,
      "oklchHue": 110,
      "oklchString": "oklch(12.0% 0.026 110.0)",
      "hue": 60.4,
      "saturation": 99.95,
      "brightness": 2.47
    }
  ],
  "yellow": [
    {
      "step": "0",
      "hex": "#fff9e1",
      "lightness": 98,
      "chroma": 0.032,
      "oklchHue": 95,
      "oklchString": "oklch(98.0% 0.032 95.0)",
      "hue": 47.7,
      "saturation": 11.75,
      "brightness": 99.98
    },
    {
      "step": "25",
      "hex": "#fff6d8",
      "lightness": 97.3,
      "chroma": 0.041,
      "oklchHue": 94.4,
      "oklchString": "oklch(97.3% 0.041 94.4)",
      "hue": 47.1,
      "saturation": 15.31,
      "brightness": 99.92
    },
    {
      "step": "50",
      "hex": "#fff4ce",
      "lightness": 96.6,
      "chroma": 0.05,
      "oklchHue": 93.9,
      "oklchString": "oklch(96.6% 0.050 93.9)",
      "hue": 46.6,
      "saturation": 18.94,
      "brightness": 99.9
    },
    {
      "step": "100",
      "hex": "#ffefbc",
      "lightness": 95.2,
      "chroma": 0.068,
      "oklchHue": 92.8,
      "oklchString": "oklch(95.2% 0.068 92.8)",
      "hue": 45.7,
      "saturation": 26.46,
      "brightness": 99.99
    },
    {
      "step": "150",
      "hex": "#ffe28d",
      "lightness": 91.9,
      "chroma": 0.109,
      "oklchHue": 91.7,
      "oklchString": "oklch(91.9% 0.109 91.7)",
      "hue": 45,
      "saturation": 44.48,
      "brightness": 99.85
    },
    {
      "step": "200",
      "hex": "#ffd555",
      "lightness": 88.6,
      "chroma": 0.15,
      "oklchHue": 90.6,
      "oklchString": "oklch(88.6% 0.150 90.6)",
      "hue": 45.1,
      "saturation": 66.84,
      "brightness": 99.99
    },
    {
      "step": "250",
      "hex": "#efc238",
      "lightness": 83.1,
      "chroma": 0.154,
      "oklchHue": 89.4,
      "oklchString": "oklch(83.1% 0.154 89.4)",
      "hue": 45.1,
      "saturation": 76.49,
      "brightness": 93.77
    },
    {
      "step": "300",
      "hex": "#dfaf08",
      "lightness": 77.6,
      "chroma": 0.157,
      "oklchHue": 88.3,
      "oklchString": "oklch(77.6% 0.157 88.3)",
      "hue": 46.5,
      "saturation": 96.33,
      "brightness": 87.62
    },
    {
      "step": "350",
      "hex": "#c59805",
      "lightness": 70.3,
      "chroma": 0.143,
      "oklchHue": 87.2,
      "oklchString": "oklch(70.3% 0.143 87.2)",
      "hue": 45.9,
      "saturation": 97.41,
      "brightness": 77.25
    },
    {
      "step": "400",
      "hex": "#ab8203",
      "lightness": 62.9,
      "chroma": 0.128,
      "oklchHue": 86.1,
      "oklchString": "oklch(62.9% 0.128 86.1)",
      "hue": 45.4,
      "saturation": 98.27,
      "brightness": 67.01
    },
    {
      "step": "450",
      "hex": "#8e6a03",
      "lightness": 54.7,
      "chroma": 0.111,
      "oklchHue": 85,
      "oklchString": "oklch(54.7% 0.111 85.0)",
      "hue": 44.6,
      "saturation": 98.12,
      "brightness": 55.84
    },
    {
      "step": "500",
      "hex": "#735402",
      "lightness": 46.6,
      "chroma": 0.095,
      "oklchHue": 83.9,
      "oklchString": "oklch(46.6% 0.095 83.9)",
      "hue": 43.7,
      "saturation": 98.04,
      "brightness": 44.94
    },
    {
      "step": "550",
      "hex": "#5b4101",
      "lightness": 39.3,
      "chroma": 0.08,
      "oklchHue": 82.8,
      "oklchString": "oklch(39.3% 0.080 82.8)",
      "hue": 42.8,
      "saturation": 98.87,
      "brightness": 35.54
    },
    {
      "step": "600",
      "hex": "#442f00",
      "lightness": 32,
      "chroma": 0.066,
      "oklchHue": 81.7,
      "oklchString": "oklch(32.0% 0.066 81.7)",
      "hue": 41.5,
      "saturation": 99.61,
      "brightness": 26.47
    },
    {
      "step": "650",
      "hex": "#332200",
      "lightness": 26.6,
      "chroma": 0.055,
      "oklchHue": 80.6,
      "oklchString": "oklch(26.6% 0.055 80.6)",
      "hue": 39.8,
      "saturation": 99.53,
      "brightness": 20.04
    },
    {
      "step": "700",
      "hex": "#231600",
      "lightness": 21.2,
      "chroma": 0.044,
      "oklchHue": 79.4,
      "oklchString": "oklch(21.2% 0.044 79.4)",
      "hue": 37.3,
      "saturation": 99.52,
      "brightness": 13.87
    },
    {
      "step": "750",
      "hex": "#1a0f00",
      "lightness": 18,
      "chroma": 0.037,
      "oklchHue": 78.3,
      "oklchString": "oklch(18.0% 0.037 78.3)",
      "hue": 34.4,
      "saturation": 99.54,
      "brightness": 10.32
    },
    {
      "step": "800",
      "hex": "#120900",
      "lightness": 14.7,
      "chroma": 0.03,
      "oklchHue": 77.2,
      "oklchString": "oklch(14.7% 0.030 77.2)",
      "hue": 29.3,
      "saturation": 99.58,
      "brightness": 6.9
    },
    {
      "step": "850",
      "hex": "#0e0600",
      "lightness": 13.4,
      "chroma": 0.028,
      "oklchHue": 76.1,
      "oklchString": "oklch(13.4% 0.028 76.1)",
      "hue": 26.9,
      "saturation": 99.66,
      "brightness": 5.55
    },
    {
      "step": "900",
      "hex": "#0b0500",
      "lightness": 12,
      "chroma": 0.025,
      "oklchHue": 75,
      "oklchString": "oklch(12.0% 0.025 75.0)",
      "hue": 25.3,
      "saturation": 99.75,
      "brightness": 4.22
    }
  ],
  "orange": [
    {
      "step": "0",
      "hex": "#ffebd5",
      "lightness": 95,
      "chroma": 0.036,
      "oklchHue": 70,
      "oklchString": "oklch(95.0% 0.036 70.0)",
      "hue": 31.4,
      "saturation": 16.48,
      "brightness": 99.96
    },
    {
      "step": "25",
      "hex": "#ffe8d0",
      "lightness": 94.3,
      "chroma": 0.04,
      "oklchHue": 68.9,
      "oklchString": "oklch(94.3% 0.040 68.9)",
      "hue": 30.8,
      "saturation": 18.39,
      "brightness": 99.93
    },
    {
      "step": "50",
      "hex": "#ffe5cb",
      "lightness": 93.7,
      "chroma": 0.044,
      "oklchHue": 67.8,
      "oklchString": "oklch(93.7% 0.044 67.8)",
      "hue": 30.3,
      "saturation": 20.29,
      "brightness": 99.92
    },
    {
      "step": "100",
      "hex": "#ffdfc1",
      "lightness": 92.3,
      "chroma": 0.053,
      "oklchHue": 65.6,
      "oklchString": "oklch(92.3% 0.053 65.6)",
      "hue": 29.2,
      "saturation": 24.07,
      "brightness": 99.94
    },
    {
      "step": "150",
      "hex": "#ffd1a9",
      "lightness": 89.1,
      "chroma": 0.074,
      "oklchHue": 63.3,
      "oklchString": "oklch(89.1% 0.074 63.3)",
      "hue": 28.3,
      "saturation": 33.74,
      "brightness": 99.92
    },
    {
      "step": "200",
      "hex": "#ffc390",
      "lightness": 85.9,
      "chroma": 0.095,
      "oklchHue": 61.1,
      "oklchString": "oklch(85.9% 0.095 61.1)",
      "hue": 27.4,
      "saturation": 43.38,
      "brightness": 99.91
    },
    {
      "step": "250",
      "hex": "#ffa963",
      "lightness": 80.6,
      "chroma": 0.133,
      "oklchHue": 58.9,
      "oklchString": "oklch(80.6% 0.133 58.9)",
      "hue": 27.2,
      "saturation": 61.21,
      "brightness": 99.89
    },
    {
      "step": "300",
      "hex": "#ff8d22",
      "lightness": 75.3,
      "chroma": 0.173,
      "oklchHue": 56.7,
      "oklchString": "oklch(75.3% 0.173 56.7)",
      "hue": 29.2,
      "saturation": 86.7,
      "brightness": 99.95
    },
    {
      "step": "350",
      "hex": "#e47814",
      "lightness": 68.2,
      "chroma": 0.165,
      "oklchHue": 54.4,
      "oklchString": "oklch(68.2% 0.165 54.4)",
      "hue": 28.8,
      "saturation": 91.37,
      "brightness": 89.44
    },
    {
      "step": "400",
      "hex": "#ca6201",
      "lightness": 61.1,
      "chroma": 0.156,
      "oklchHue": 52.2,
      "oklchString": "oklch(61.1% 0.156 52.2)",
      "hue": 29.1,
      "saturation": 99.36,
      "brightness": 79.03
    },
    {
      "step": "450",
      "hex": "#aa4e02",
      "lightness": 53.2,
      "chroma": 0.14,
      "oklchHue": 50,
      "oklchString": "oklch(53.2% 0.140 50.0)",
      "hue": 27.3,
      "saturation": 98.86,
      "brightness": 66.6
    },
    {
      "step": "500",
      "hex": "#8b3b01",
      "lightness": 45.4,
      "chroma": 0.124,
      "oklchHue": 47.8,
      "oklchString": "oklch(45.4% 0.124 47.8)",
      "hue": 25.5,
      "saturation": 99.54,
      "brightness": 54.47
    },
    {
      "step": "550",
      "hex": "#702c01",
      "lightness": 38.3,
      "chroma": 0.108,
      "oklchHue": 45.6,
      "oklchString": "oklch(38.3% 0.108 45.6)",
      "hue": 23.1,
      "saturation": 99.23,
      "brightness": 43.76
    },
    {
      "step": "600",
      "hex": "#551d00",
      "lightness": 31.3,
      "chroma": 0.092,
      "oklchHue": 43.3,
      "oklchString": "oklch(31.3% 0.092 43.3)",
      "hue": 20.1,
      "saturation": 99.93,
      "brightness": 33.41
    },
    {
      "step": "650",
      "hex": "#421300",
      "lightness": 26.1,
      "chroma": 0.079,
      "oklchHue": 41.1,
      "oklchString": "oklch(26.1% 0.079 41.1)",
      "hue": 16.6,
      "saturation": 99.36,
      "brightness": 25.94
    },
    {
      "step": "700",
      "hex": "#300900",
      "lightness": 20.9,
      "chroma": 0.067,
      "oklchHue": 38.9,
      "oklchString": "oklch(20.9% 0.067 38.9)",
      "hue": 11.3,
      "saturation": 99.58,
      "brightness": 18.76
    },
    {
      "step": "750",
      "hex": "#250500",
      "lightness": 17.8,
      "chroma": 0.059,
      "oklchHue": 36.7,
      "oklchString": "oklch(17.8% 0.059 36.7)",
      "hue": 7.3,
      "saturation": 99.49,
      "brightness": 14.63
    },
    {
      "step": "800",
      "hex": "#1b0200",
      "lightness": 14.6,
      "chroma": 0.052,
      "oklchHue": 34.4,
      "oklchString": "oklch(14.6% 0.052 34.4)",
      "hue": 4.2,
      "saturation": 99.76,
      "brightness": 10.63
    },
    {
      "step": "850",
      "hex": "#170100",
      "lightness": 13.3,
      "chroma": 0.05,
      "oklchHue": 32.2,
      "oklchString": "oklch(13.3% 0.050 32.2)",
      "hue": 2.3,
      "saturation": 99.79,
      "brightness": 9.15
    },
    {
      "step": "900",
      "hex": "#140000",
      "lightness": 12,
      "chroma": 0.048,
      "oklchHue": 30,
      "oklchString": "oklch(12.0% 0.048 30.0)",
      "hue": 0.6,
      "saturation": 99.89,
      "brightness": 7.69
    }
  ],
  "red": [
    {
      "step": "0",
      "hex": "#ffe9e5",
      "lightness": 95,
      "chroma": 0.025,
      "oklchHue": 30,
      "oklchString": "oklch(95.0% 0.025 30.0)",
      "hue": 9.3,
      "saturation": 10.24,
      "brightness": 99.94
    },
    {
      "step": "25",
      "hex": "#ffe6e1",
      "lightness": 94.3,
      "chroma": 0.028,
      "oklchHue": 29.7,
      "oklchString": "oklch(94.3% 0.028 29.7)",
      "hue": 9.1,
      "saturation": 11.62,
      "brightness": 99.95
    },
    {
      "step": "50",
      "hex": "#ffe3de",
      "lightness": 93.7,
      "chroma": 0.032,
      "oklchHue": 29.4,
      "oklchString": "oklch(93.7% 0.032 29.4)",
      "hue": 8.9,
      "saturation": 12.97,
      "brightness": 99.95
    },
    {
      "step": "100",
      "hex": "#ffddd7",
      "lightness": 92.3,
      "chroma": 0.039,
      "oklchHue": 28.9,
      "oklchString": "oklch(92.3% 0.039 28.9)",
      "hue": 8.5,
      "saturation": 15.62,
      "brightness": 99.91
    },
    {
      "step": "150",
      "hex": "#ffcec6",
      "lightness": 89.1,
      "chroma": 0.057,
      "oklchHue": 28.3,
      "oklchString": "oklch(89.1% 0.057 28.3)",
      "hue": 8,
      "saturation": 22.15,
      "brightness": 99.88
    },
    {
      "step": "200",
      "hex": "#ffbeb5",
      "lightness": 85.9,
      "chroma": 0.076,
      "oklchHue": 27.8,
      "oklchString": "oklch(85.9% 0.076 27.8)",
      "hue": 7.4,
      "saturation": 28.74,
      "brightness": 99.87
    },
    {
      "step": "250",
      "hex": "#ffa499",
      "lightness": 80.6,
      "chroma": 0.11,
      "oklchHue": 27.2,
      "oklchString": "oklch(80.6% 0.110 27.2)",
      "hue": 6.5,
      "saturation": 39.88,
      "brightness": 99.86
    },
    {
      "step": "300",
      "hex": "#ff877c",
      "lightness": 75.3,
      "chroma": 0.148,
      "oklchHue": 26.7,
      "oklchString": "oklch(75.3% 0.148 26.7)",
      "hue": 5.1,
      "saturation": 51.55,
      "brightness": 99.96
    },
    {
      "step": "350",
      "hex": "#fa5d56",
      "lightness": 68.2,
      "chroma": 0.193,
      "oklchHue": 26.1,
      "oklchString": "oklch(68.2% 0.193 26.1)",
      "hue": 2.6,
      "saturation": 65.74,
      "brightness": 97.88
    },
    {
      "step": "400",
      "hex": "#f2192c",
      "lightness": 61.1,
      "chroma": 0.239,
      "oklchHue": 25.6,
      "oklchString": "oklch(61.1% 0.239 25.6)",
      "hue": 354.9,
      "saturation": 89.54,
      "brightness": 94.74
    },
    {
      "step": "450",
      "hex": "#ca0c23",
      "lightness": 53.2,
      "chroma": 0.211,
      "oklchHue": 25,
      "oklchString": "oklch(53.2% 0.211 25.0)",
      "hue": 352.8,
      "saturation": 93.96,
      "brightness": 79.34
    },
    {
      "step": "500",
      "hex": "#a4001a",
      "lightness": 45.4,
      "chroma": 0.184,
      "oklchHue": 24.4,
      "oklchString": "oklch(45.4% 0.184 24.4)",
      "hue": 350.5,
      "saturation": 99.9,
      "brightness": 64.48
    },
    {
      "step": "550",
      "hex": "#820114",
      "lightness": 38.3,
      "chroma": 0.155,
      "oklchHue": 23.9,
      "oklchString": "oklch(38.3% 0.155 23.9)",
      "hue": 350.9,
      "saturation": 99.51,
      "brightness": 51.1
    },
    {
      "step": "600",
      "hex": "#62010e",
      "lightness": 31.3,
      "chroma": 0.126,
      "oklchHue": 23.3,
      "oklchString": "oklch(31.3% 0.126 23.3)",
      "hue": 351.8,
      "saturation": 99.12,
      "brightness": 38.33
    },
    {
      "step": "650",
      "hex": "#4b0109",
      "lightness": 26.1,
      "chroma": 0.105,
      "oklchHue": 22.8,
      "oklchString": "oklch(26.1% 0.105 22.8)",
      "hue": 353,
      "saturation": 99.31,
      "brightness": 29.41
    },
    {
      "step": "700",
      "hex": "#350005",
      "lightness": 20.9,
      "chroma": 0.084,
      "oklchHue": 22.2,
      "oklchString": "oklch(20.9% 0.084 22.2)",
      "hue": 354.5,
      "saturation": 99.43,
      "brightness": 20.93
    },
    {
      "step": "750",
      "hex": "#290003",
      "lightness": 17.8,
      "chroma": 0.071,
      "oklchHue": 21.7,
      "oklchString": "oklch(17.8% 0.071 21.7)",
      "hue": 355.2,
      "saturation": 99.71,
      "brightness": 16.08
    },
    {
      "step": "800",
      "hex": "#1d0002",
      "lightness": 14.6,
      "chroma": 0.059,
      "oklchHue": 21.1,
      "oklchString": "oklch(14.6% 0.059 21.1)",
      "hue": 355.9,
      "saturation": 99.94,
      "brightness": 11.44
    },
    {
      "step": "850",
      "hex": "#180002",
      "lightness": 13.3,
      "chroma": 0.053,
      "oklchHue": 20.6,
      "oklchString": "oklch(13.3% 0.053 20.6)",
      "hue": 356,
      "saturation": 99.86,
      "brightness": 9.53
    },
    {
      "step": "900",
      "hex": "#140001",
      "lightness": 12,
      "chroma": 0.048,
      "oklchHue": 20,
      "oklchString": "oklch(12.0% 0.048 20.0)",
      "hue": 356.1,
      "saturation": 99.76,
      "brightness": 7.67
    }
  ],
  "fuschia": [
    {
      "step": "0",
      "hex": "#ffe7f1",
      "lightness": 95,
      "chroma": 0.029,
      "oklchHue": 350,
      "oklchString": "oklch(95.0% 0.029 350.0)",
      "hue": 334.5,
      "saturation": 9.43,
      "brightness": 99.99
    },
    {
      "step": "25",
      "hex": "#ffe4f0",
      "lightness": 94.3,
      "chroma": 0.034,
      "oklchHue": 348.6,
      "oklchString": "oklch(94.3% 0.034 348.6)",
      "hue": 332.8,
      "saturation": 10.76,
      "brightness": 99.99
    },
    {
      "step": "50",
      "hex": "#ffe0ef",
      "lightness": 93.7,
      "chroma": 0.039,
      "oklchHue": 347.2,
      "oklchString": "oklch(93.7% 0.039 347.2)",
      "hue": 331.2,
      "saturation": 12.01,
      "brightness": 99.93
    },
    {
      "step": "100",
      "hex": "#ffd9ee",
      "lightness": 92.3,
      "chroma": 0.049,
      "oklchHue": 344.4,
      "oklchString": "oklch(92.3% 0.049 344.4)",
      "hue": 327.7,
      "saturation": 14.84,
      "brightness": 99.98
    },
    {
      "step": "150",
      "hex": "#ffc8e9",
      "lightness": 89.1,
      "chroma": 0.075,
      "oklchHue": 341.7,
      "oklchString": "oklch(89.1% 0.075 341.7)",
      "hue": 323.5,
      "saturation": 21.37,
      "brightness": 99.89
    },
    {
      "step": "200",
      "hex": "#ffb6e8",
      "lightness": 85.9,
      "chroma": 0.104,
      "oklchHue": 338.9,
      "oklchString": "oklch(85.9% 0.104 338.9)",
      "hue": 319.1,
      "saturation": 28.49,
      "brightness": 99.9
    },
    {
      "step": "250",
      "hex": "#ff96e6",
      "lightness": 80.6,
      "chroma": 0.159,
      "oklchHue": 336.1,
      "oklchString": "oklch(80.6% 0.159 336.1)",
      "hue": 313.9,
      "saturation": 41.24,
      "brightness": 99.82
    },
    {
      "step": "300",
      "hex": "#ff6cea",
      "lightness": 75.3,
      "chroma": 0.226,
      "oklchHue": 333.3,
      "oklchString": "oklch(75.3% 0.226 333.3)",
      "hue": 308.4,
      "saturation": 57.41,
      "brightness": 99.86
    },
    {
      "step": "350",
      "hex": "#e84bde",
      "lightness": 68.2,
      "chroma": 0.246,
      "oklchHue": 330.6,
      "oklchString": "oklch(68.2% 0.246 330.6)",
      "hue": 303.8,
      "saturation": 67.4,
      "brightness": 90.81
    },
    {
      "step": "400",
      "hex": "#d01fd2",
      "lightness": 61.1,
      "chroma": 0.267,
      "oklchHue": 327.8,
      "oklchString": "oklch(61.1% 0.267 327.8)",
      "hue": 299.4,
      "saturation": 85.24,
      "brightness": 82.26
    },
    {
      "step": "450",
      "hex": "#ab12b6",
      "lightness": 53.2,
      "chroma": 0.24,
      "oklchHue": 325,
      "oklchString": "oklch(53.2% 0.240 325.0)",
      "hue": 296.1,
      "saturation": 90.1,
      "brightness": 71.38
    },
    {
      "step": "500",
      "hex": "#89029a",
      "lightness": 45.4,
      "chroma": 0.214,
      "oklchHue": 322.2,
      "oklchString": "oklch(45.4% 0.214 322.2)",
      "hue": 293.3,
      "saturation": 98.41,
      "brightness": 60.25
    },
    {
      "step": "550",
      "hex": "#6a027e",
      "lightness": 38.3,
      "chroma": 0.183,
      "oklchHue": 319.4,
      "oklchString": "oklch(38.3% 0.183 319.4)",
      "hue": 290.3,
      "saturation": 98.18,
      "brightness": 49.39
    },
    {
      "step": "600",
      "hex": "#4d0162",
      "lightness": 31.3,
      "chroma": 0.151,
      "oklchHue": 316.7,
      "oklchString": "oklch(31.3% 0.151 316.7)",
      "hue": 287.2,
      "saturation": 98.84,
      "brightness": 38.44
    },
    {
      "step": "650",
      "hex": "#39014e",
      "lightness": 26.1,
      "chroma": 0.128,
      "oklchHue": 313.9,
      "oklchString": "oklch(26.1% 0.128 313.9)",
      "hue": 284,
      "saturation": 99.1,
      "brightness": 30.57
    },
    {
      "step": "700",
      "hex": "#27003a",
      "lightness": 20.9,
      "chroma": 0.105,
      "oklchHue": 311.1,
      "oklchString": "oklch(20.9% 0.105 311.1)",
      "hue": 280.4,
      "saturation": 99.78,
      "brightness": 22.71
    },
    {
      "step": "750",
      "hex": "#1c002e",
      "lightness": 17.8,
      "chroma": 0.09,
      "oklchHue": 308.3,
      "oklchString": "oklch(17.8% 0.090 308.3)",
      "hue": 276.6,
      "saturation": 99.63,
      "brightness": 18.12
    },
    {
      "step": "800",
      "hex": "#120022",
      "lightness": 14.6,
      "chroma": 0.075,
      "oklchHue": 305.6,
      "oklchString": "oklch(14.6% 0.075 305.6)",
      "hue": 271.8,
      "saturation": 99.75,
      "brightness": 13.52
    },
    {
      "step": "850",
      "hex": "#0e001e",
      "lightness": 13.3,
      "chroma": 0.07,
      "oklchHue": 302.8,
      "oklchString": "oklch(13.3% 0.070 302.8)",
      "hue": 267.6,
      "saturation": 99.83,
      "brightness": 11.85
    },
    {
      "step": "900",
      "hex": "#0a001a",
      "lightness": 12,
      "chroma": 0.064,
      "oklchHue": 300,
      "oklchString": "oklch(12.0% 0.064 300.0)",
      "hue": 262.8,
      "saturation": 99.99,
      "brightness": 10.15
    }
  ],
  "purple": [
    {
      "step": "0",
      "hex": "#f1ebff",
      "lightness": 95,
      "chroma": 0.028,
      "oklchHue": 300,
      "oklchString": "oklch(95.0% 0.028 300.0)",
      "hue": 258.6,
      "saturation": 7.9,
      "brightness": 99.94
    },
    {
      "step": "25",
      "hex": "#efe8ff",
      "lightness": 94.3,
      "chroma": 0.031,
      "oklchHue": 299.4,
      "oklchString": "oklch(94.3% 0.031 299.4)",
      "hue": 258,
      "saturation": 8.93,
      "brightness": 99.94
    },
    {
      "step": "50",
      "hex": "#ede5ff",
      "lightness": 93.7,
      "chroma": 0.035,
      "oklchHue": 298.9,
      "oklchString": "oklch(93.7% 0.035 298.9)",
      "hue": 257.3,
      "saturation": 9.97,
      "brightness": 99.94
    },
    {
      "step": "100",
      "hex": "#e8e0ff",
      "lightness": 92.3,
      "chroma": 0.042,
      "oklchHue": 297.8,
      "oklchString": "oklch(92.3% 0.042 297.8)",
      "hue": 256,
      "saturation": 12.02,
      "brightness": 99.96
    },
    {
      "step": "150",
      "hex": "#ded4ff",
      "lightness": 89.1,
      "chroma": 0.06,
      "oklchHue": 296.7,
      "oklchString": "oklch(89.1% 0.060 296.7)",
      "hue": 255.1,
      "saturation": 16.93,
      "brightness": 99.9
    },
    {
      "step": "200",
      "hex": "#d4c7ff",
      "lightness": 85.9,
      "chroma": 0.077,
      "oklchHue": 295.6,
      "oklchString": "oklch(85.9% 0.077 295.6)",
      "hue": 254.2,
      "saturation": 21.78,
      "brightness": 99.83
    },
    {
      "step": "250",
      "hex": "#c4b2ff",
      "lightness": 80.6,
      "chroma": 0.108,
      "oklchHue": 294.4,
      "oklchString": "oklch(80.6% 0.108 294.4)",
      "hue": 253.9,
      "saturation": 30.16,
      "brightness": 99.96
    },
    {
      "step": "300",
      "hex": "#b39dff",
      "lightness": 75.3,
      "chroma": 0.14,
      "oklchHue": 293.3,
      "oklchString": "oklch(75.3% 0.140 293.3)",
      "hue": 253.8,
      "saturation": 38.5,
      "brightness": 99.92
    },
    {
      "step": "350",
      "hex": "#9e7efe",
      "lightness": 68.2,
      "chroma": 0.183,
      "oklchHue": 292.2,
      "oklchString": "oklch(68.2% 0.183 292.2)",
      "hue": 254.8,
      "saturation": 50.25,
      "brightness": 99.71
    },
    {
      "step": "400",
      "hex": "#8a5cff",
      "lightness": 61.1,
      "chroma": 0.229,
      "oklchHue": 291.1,
      "oklchString": "oklch(61.1% 0.229 291.1)",
      "hue": 257,
      "saturation": 63.95,
      "brightness": 99.92
    },
    {
      "step": "450",
      "hex": "#733ceb",
      "lightness": 53.2,
      "chroma": 0.243,
      "oklchHue": 290,
      "oklchString": "oklch(53.2% 0.243 290.0)",
      "hue": 259,
      "saturation": 74.63,
      "brightness": 92.12
    },
    {
      "step": "500",
      "hex": "#5e05d7",
      "lightness": 45.4,
      "chroma": 0.256,
      "oklchHue": 288.9,
      "oklchString": "oklch(45.4% 0.256 288.9)",
      "hue": 265.5,
      "saturation": 97.79,
      "brightness": 84.3
    },
    {
      "step": "550",
      "hex": "#4803ad",
      "lightness": 38.3,
      "chroma": 0.218,
      "oklchHue": 287.8,
      "oklchString": "oklch(38.3% 0.218 287.8)",
      "hue": 264.3,
      "saturation": 98.27,
      "brightness": 67.82
    },
    {
      "step": "600",
      "hex": "#330184",
      "lightness": 31.3,
      "chroma": 0.18,
      "oklchHue": 286.7,
      "oklchString": "oklch(31.3% 0.180 286.7)",
      "hue": 263,
      "saturation": 99.09,
      "brightness": 51.94
    },
    {
      "step": "650",
      "hex": "#250168",
      "lightness": 26.1,
      "chroma": 0.151,
      "oklchHue": 285.6,
      "oklchString": "oklch(26.1% 0.151 285.6)",
      "hue": 261.2,
      "saturation": 99.19,
      "brightness": 40.62
    },
    {
      "step": "700",
      "hex": "#18004c",
      "lightness": 20.9,
      "chroma": 0.122,
      "oklchHue": 284.4,
      "oklchString": "oklch(20.9% 0.122 284.4)",
      "hue": 258.7,
      "saturation": 99.54,
      "brightness": 29.76
    },
    {
      "step": "750",
      "hex": "#10003c",
      "lightness": 17.8,
      "chroma": 0.104,
      "oklchHue": 283.3,
      "oklchString": "oklch(17.8% 0.104 283.3)",
      "hue": 256.1,
      "saturation": 99.6,
      "brightness": 23.48
    },
    {
      "step": "800",
      "hex": "#09002c",
      "lightness": 14.6,
      "chroma": 0.087,
      "oklchHue": 282.2,
      "oklchString": "oklch(14.6% 0.087 282.2)",
      "hue": 252.2,
      "saturation": 99.78,
      "brightness": 17.43
    },
    {
      "step": "850",
      "hex": "#060026",
      "lightness": 13.3,
      "chroma": 0.079,
      "oklchHue": 281.1,
      "oklchString": "oklch(13.3% 0.079 281.1)",
      "hue": 250,
      "saturation": 99.78,
      "brightness": 15.03
    },
    {
      "step": "900",
      "hex": "#040020",
      "lightness": 12,
      "chroma": 0.072,
      "oklchHue": 280,
      "oklchString": "oklch(12.0% 0.072 280.0)",
      "hue": 248.1,
      "saturation": 99.84,
      "brightness": 12.66
    }
  ],
  "gray": [
    {
      "step": "0",
      "hex": "#eeeeee",
      "lightness": 95,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(95.0% 0.000 0.0)",
      "hue": 120,
      "saturation": 0,
      "brightness": 93.45
    },
    {
      "step": "25",
      "hex": "#ececec",
      "lightness": 94.3,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(94.3% 0.000 0.0)",
      "hue": 345.1,
      "saturation": 0,
      "brightness": 92.58
    },
    {
      "step": "50",
      "hex": "#eaeaea",
      "lightness": 93.7,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(93.7% 0.000 0.0)",
      "hue": 345.1,
      "saturation": 0,
      "brightness": 91.71
    },
    {
      "step": "100",
      "hex": "#e5e5e5",
      "lightness": 92.3,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(92.3% 0.000 0.0)",
      "hue": 120,
      "saturation": 0,
      "brightness": 89.97
    },
    {
      "step": "150",
      "hex": "#dbdbdb",
      "lightness": 89.1,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(89.1% 0.000 0.0)",
      "hue": 345.1,
      "saturation": 0,
      "brightness": 85.85
    },
    {
      "step": "200",
      "hex": "#d0d0d0",
      "lightness": 85.9,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(85.9% 0.000 0.0)",
      "hue": 0,
      "saturation": 0,
      "brightness": 81.76
    },
    {
      "step": "250",
      "hex": "#bfbfbf",
      "lightness": 80.6,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(80.6% 0.000 0.0)",
      "hue": 345.1,
      "saturation": 0,
      "brightness": 75.1
    },
    {
      "step": "300",
      "hex": "#afafaf",
      "lightness": 75.3,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(75.3% 0.000 0.0)",
      "hue": 0,
      "saturation": 0,
      "brightness": 68.55
    },
    {
      "step": "350",
      "hex": "#999999",
      "lightness": 68.2,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(68.2% 0.000 0.0)",
      "hue": 345.1,
      "saturation": 0,
      "brightness": 59.91
    },
    {
      "step": "400",
      "hex": "#838383",
      "lightness": 61.1,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(61.1% 0.000 0.0)",
      "hue": 0,
      "saturation": 0,
      "brightness": 51.49
    },
    {
      "step": "450",
      "hex": "#6c6c6c",
      "lightness": 53.2,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(53.2% 0.000 0.0)",
      "hue": 345.1,
      "saturation": 0,
      "brightness": 42.48
    },
    {
      "step": "500",
      "hex": "#565656",
      "lightness": 45.4,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(45.4% 0.000 0.0)",
      "hue": 120,
      "saturation": 0,
      "brightness": 33.8
    },
    {
      "step": "550",
      "hex": "#434343",
      "lightness": 38.3,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(38.3% 0.000 0.0)",
      "hue": 345.1,
      "saturation": 0,
      "brightness": 26.34
    },
    {
      "step": "600",
      "hex": "#313131",
      "lightness": 31.3,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(31.3% 0.000 0.0)",
      "hue": 120,
      "saturation": 0,
      "brightness": 19.21
    },
    {
      "step": "650",
      "hex": "#242424",
      "lightness": 26.1,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(26.1% 0.000 0.0)",
      "hue": 345.1,
      "saturation": 0,
      "brightness": 14.19
    },
    {
      "step": "700",
      "hex": "#181818",
      "lightness": 20.9,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(20.9% 0.000 0.0)",
      "hue": 180,
      "saturation": 0,
      "brightness": 9.42
    },
    {
      "step": "750",
      "hex": "#111111",
      "lightness": 17.8,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(17.8% 0.000 0.0)",
      "hue": 345.1,
      "saturation": 0,
      "brightness": 6.68
    },
    {
      "step": "800",
      "hex": "#0a0a0a",
      "lightness": 14.6,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(14.6% 0.000 0.0)",
      "hue": 240,
      "saturation": 0,
      "brightness": 4.05
    },
    {
      "step": "850",
      "hex": "#080808",
      "lightness": 13.3,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(13.3% 0.000 0.0)",
      "hue": 345.1,
      "saturation": 0,
      "brightness": 3.05
    },
    {
      "step": "900",
      "hex": "#060606",
      "lightness": 12,
      "chroma": 0,
      "oklchHue": 0,
      "oklchString": "oklch(12.0% 0.000 0.0)",
      "hue": 0,
      "saturation": 0,
      "brightness": 2.23
    }
  ]
};

const formatOklch = (l: number, c: number, h: number) => {
    return {
        '$type': 'color',
        '$value': {
            colorSpace: "oklch",
            components: [l, c, h],
            alpha: 1
        }
    }
}

let palette = Object.keys(colorBoxOutput).reduce((prior, colorLabel) => {
  const compiledColorObj = colorBoxOutput[colorLabel] && Object.fromEntries(colorBoxOutput[colorLabel].map((color: any) => {
    return [color.step, formatOklch(color.lightness / 100, color.chroma, color.oklchHue)];
  }));
  return Object.assign({}, prior, { [colorLabel]: compiledColorObj });
}, {});

// @ts-expect-error
palette['white'] = formatOklch(1, 0, 0);
// @ts-expect-error
palette['black'] = formatOklch(0, 0, 0);

export default {
    color: palette
} as TokenSet;
