import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Generates the curated icon set from @phosphor-icons/core, which is a
 * devDependency — the artwork is emitted as path data here, so nothing about
 * Phosphor survives into the published package's dependency graph.
 *
 * Phosphor's regular and fill weights are each a single <path> carrying only a
 * `d` attribute, so that is all we need to keep. Run after changing NAMES.
 */

const WEIGHTS = ['regular', 'fill'];

/** Curated set. Names are Phosphor's own, so there is nothing to translate. */
const NAMES = [
  'caret-down', 'caret-up', 'caret-left', 'caret-right',
  'arrow-down', 'arrow-up', 'arrow-left', 'arrow-right',
  'x', 'check', 'plus', 'minus',
  'copy', 'check-circle', 'warning', 'warning-circle', 'info', 'question',
  'magnifying-glass', 'gear', 'user', 'calendar', 'clock',
  'trash', 'pencil-simple', 'list', 'arrow-square-out', 'sun', 'moon',
  // Toggle affordances, where the fill weight carries the pressed state.
  'star', 'heart', 'eye', 'eye-slash', 'bell',
];

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, '../src/icon/generated');
const require = createRequire(import.meta.url);

function phosphorRoot() {
  try {
    return dirname(require.resolve('@phosphor-icons/core/package.json'));
  } catch {
    // The package may not expose ./package.json through its exports map.
    return resolve(dirname(require.resolve('@phosphor-icons/core')), '..');
  }
}

const root = phosphorRoot();

const camel = (name) => name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

function pathData(name, weight) {
  // Only the regular weight is unsuffixed on disk.
  const file = resolve(root, 'assets', weight, weight === 'regular' ? `${name}.svg` : `${name}-${weight}.svg`);
  if (!existsSync(file)) throw new Error(`No "${weight}" weight for icon "${name}" (looked in ${file})`);

  const svg = readFileSync(file, 'utf8');
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length !== 1) throw new Error(`Expected exactly one path in ${file}, found ${paths.length}`);

  return paths[0];
}

const header = `// Generated by scripts/generate-icons.mjs — do not edit by hand.
// Artwork from Phosphor Icons (https://phosphoricons.com), MIT licensed.
`;

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

for (const name of NAMES) {
  const weights = WEIGHTS.map((w) => `  ${w}: '${pathData(name, w)}',`).join('\n');
  writeFileSync(
    resolve(outDir, `${name}.ts`),
    `${header}\nexport const ${camel(name)} = {\n${weights}\n};\n`,
    'utf8'
  );
}

// The registry backs <Icon icon="name" />. Jig's own components should import
// a single icon module directly instead, so using one icon internally does not
// pull the whole set into the core bundle.
const imports = NAMES.map((n) => `import { ${camel(n)} } from './${n}';`).join('\n');
const entries = NAMES.map((n) => `  '${n}': ${camel(n)},`).join('\n');

writeFileSync(
  resolve(outDir, 'index.ts'),
  `${header}\n${imports}\n\nexport const icons = {\n${entries}\n};\n\nexport type IconName = keyof typeof icons;\n`,
  'utf8'
);

console.log(`Icons generated: \x1b[32m ${NAMES.length} icons × ${WEIGHTS.length} weights \x1b[0m`);
